apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5175       
      targetPort: 5173 
      nodePort: 31000   
  type: NodePort
